# Generated by Django 2.1 on 2020-05-09 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=264)),
                ('employee_count', models.IntegerField(default=0, editable=False)),
            ],
        ),
        migrations.AlterField(
            model_name='employeejobinfo',
            name='working_hours',
            field=models.CharField(choices=[('F', 'Full Time'), ('P', 'Part Time'), ('c', 'Contract Based')], max_length=25),
        ),
        migrations.AddField(
            model_name='employeejobinfo',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Department'),
        ),
    ]
