# Generated by Django 2.1 on 2020-05-09 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200509_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='employee_count',
        ),
    ]
