# Generated by Django 2.1 on 2020-11-02 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_departmentmanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentmanager',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Department'),
        ),
    ]
