# Generated by Django 2.1 on 2020-05-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200519_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepersonalinfo',
            name='image',
            field=models.ImageField(default='default.png', upload_to='profile_pics'),
        ),
    ]
