# Generated by Django 2.1 on 2020-05-19 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200519_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paygrade',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
