# Generated by Django 2.1 on 2020-11-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createMode', '0002_taskreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='review_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
