# Generated by Django 2.1 on 2020-11-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createMode', '0003_auto_20201118_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
