# Generated by Django 2.1 on 2020-11-28 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createMode', '0004_auto_20201128_0938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='accepted',
            new_name='is_accepted',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='rejected',
            new_name='is_rejected',
        ),
    ]
