# Generated by Django 2.1 on 2020-11-28 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('createMode', '0005_auto_20201128_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskRejectFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField()),
                ('rejected_on', models.DateTimeField(auto_now_add=True)),
                ('rejected_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejected_by_user', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createMode.Task')),
            ],
        ),
    ]
