# Generated by Django 2.1 on 2020-12-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createMode', '0007_task_reject_feedback_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='resources',
            field=models.FileField(blank=True, null=True, upload_to='resources'),
        ),
    ]
